# Generated by Django 4.1.6 on 2023-11-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
