# Generated by Django 4.1.6 on 2023-11-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0006_tag_parent_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parent_tag',
        ),
        migrations.CreateModel(
            name='Subtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='eventblog.tag')),
            ],
            options={
                'verbose_name': 'subtag',
                'verbose_name_plural': 'subtags',
                'ordering': ('name',),
            },
        ),
    ]
