# Generated by Django 4.1.6 on 2023-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0007_remove_tag_parent_tag_subtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='eventblog.subtag'),
        ),
    ]
