# Generated by Django 4.1.6 on 2023-11-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0008_alter_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='subtag',
        ),
    ]
