# Generated by Django 4.1.6 on 2023-11-27 15:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0009_rename_tag_post_subtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('featured_image', models.ImageField(default='', upload_to='images/')),
                ('created_at', models.DateField(auto_now=True)),
                ('subtag', models.ManyToManyField(to='eventblog.subtag')),
            ],
        ),
    ]
