# Generated by Django 4.1.6 on 2023-11-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
