# Generated by Django 4.1.6 on 2023-11-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0011_remove_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
