# Generated by Django 4.1.6 on 2023-11-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0012_remove_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
