# Generated by Django 4.1.6 on 2023-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0013_alter_contact_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
