# Generated by Django 4.1.6 on 2023-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0014_alter_contact_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='featured_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
