# Generated by Django 4.1.6 on 2023-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0015_alter_contact_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_info',
            field=models.CharField(default='', max_length=400),
        ),
    ]
