# Generated by Django 4.1.6 on 2023-11-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0016_contact_contact_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_info',
            new_name='your_contact_info',
        ),
    ]
