# Generated by Django 4.1.6 on 2023-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0017_rename_contact_info_contact_your_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='your_contact_info',
        ),
        migrations.AddField(
            model_name='contact',
            name='your_name_and_contact_information',
            field=models.TextField(default='', max_length=400),
        ),
    ]
