# Generated by Django 4.1.6 on 2023-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0018_remove_contact_your_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='your_name_and_contact_information',
            field=models.CharField(default='', max_length=400),
        ),
    ]
