# Generated by Django 4.1.6 on 2023-11-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0019_alter_contact_your_name_and_contact_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subtag',
            new_name='pear_tag',
        ),
    ]
