# Generated by Django 4.1.6 on 2023-11-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0020_rename_subtag_contact_pear_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pear_tag',
            new_name='pear_tags',
        ),
    ]
