# Generated by Django 4.1.6 on 2023-11-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0021_rename_pear_tag_contact_pear_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
    ]
