# Generated by Django 4.1.6 on 2023-11-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0022_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
