# Generated by Django 4.1.6 on 2023-11-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0024_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Questions',
        ),
    ]
