# Generated by Django 4.1.6 on 2023-11-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0025_rename_about_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
