# Generated by Django 4.1.6 on 2023-11-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0026_rename_questions_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Submission',
        ),
    ]
