# Generated by Django 4.1.6 on 2023-11-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0027_rename_contact_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='your_name_and_contact_information',
        ),
        migrations.AddField(
            model_name='submission',
            name='contact_information',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='your_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
