# Generated by Django 4.1.6 on 2023-11-30 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0028_remove_submission_your_name_and_contact_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='check_if_you_are_the_event_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='event_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 8, 31, 54, 771263)),
        ),
        migrations.AddField(
            model_name='submission',
            name='event_setup_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 8, 31, 54, 771263)),
        ),
        migrations.AddField(
            model_name='submission',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='vendor_fee',
            field=models.CharField(default='', max_length=200),
        ),
    ]
