# Generated by Django 4.1.6 on 2023-11-30 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0029_submission_check_if_you_are_the_event_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='content',
            new_name='additional_information',
        ),
        migrations.AddField(
            model_name='submission',
            name='event_host_contact_information',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='event_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 8, 33, 40, 114912)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='event_setup_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 8, 33, 40, 114912)),
        ),
    ]
