# Generated by Django 4.1.6 on 2023-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0030_rename_content_submission_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='event_date_and_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='event_setup_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
