# Generated by Django 4.1.6 on 2023-11-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0031_alter_submission_event_date_and_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='additional_information',
            new_name='additional_information_or_pear_tags',
        ),
    ]
