# Generated by Django 4.1.6 on 2023-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0032_rename_additional_information_submission_additional_information_or_pear_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='additional_information_or_pear_tags',
            new_name='additional_information',
        ),
        migrations.AddField(
            model_name='submission',
            name='additional_pear_tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
