# Generated by Django 4.1.6 on 2023-11-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventblog', '0033_rename_additional_information_or_pear_tags_submission_additional_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='featured_image',
            new_name='event_flyer',
        ),
    ]
